export const ROUTES = {
  root: '/',
  roles: '/roles',
  login: '/login',
  forgotPassword: '/forgot-password',
  otpVerification: '/otp-verification',
  resetPassword: '/reset-password',
  passwordResetSuccess: '/password-reset-success',
  dashboard: '/dashboard',
  partners: '/partners',
  partnerDetails: '/partner-details',
  approvalQueue: '/partners/approval-queue',
  fraudCenter: '/fraud-detection',
  communications: '/communications',
  settlements: '/wallet/settlements',
  analytics: '/analytics',
  users: '/users',
  kyc: '/kyc',
  business: '/business',
  businessApproval: '/business/approval',
  businessDetails: '/business/details',
  businessReview: '/business/review',
  businessVerify: '/business/verify',
  businessSuspension: '/business/suspension',
  businessRisk: '/business/risk-management',
  addBusiness: '/business/add',
  businessDocReview: '/business/review/document',
  businessTaxonomy: '/business/taxonomy',
  branches: '/branches',
  services: '/services',
  employees: '/employees',
  bookings: '/bookings',
  liveTracking: '/live-tracking',
  materials: '/materials',
  quotations: '/quotations',
  wallet: '/wallet',
  banking: '/banking',
  revenue: '/revenue',
  referrals: '/referrals',
  notifications: '/notifications',
  banners: '/banners',
  cms: '/cms',
  reviews: '/reviews',
  sos: '/sos',
  support: '/support',
  settings: '/settings',
  performance: '/performance',
  reports: '/reports',
  attendance: '/attendance',
  leaveManagement: '/leave-management',
  branchPerformance: '/branches/performance',
  branchApproval: '/branches/approval',
  branchAnalytics: '/branches/analytics',
  branchSchedule: '/branches/schedule',
  branchSuspend: '/branches/suspend',
  branchCompliance: '/branches/compliance',
  branchProfile: '/branches/profile',
  branchManagerAssignment: '/branches/assign-manager',
  serviceAreas: '/service-areas',
  branchServiceAreas: '/branches/service-areas',
  branchCoverage: '/branches/coverage',

  // --- NEW MODULE SUB-ROUTES ---

  // Dashboard sub-routes
  dashboardRevenue: '/dashboard/revenue',
  dashboardBookings: '/dashboard/bookings',
  dashboardUsers: '/dashboard/users-analytics',
  dashboardPartners: '/dashboard/partners-analytics',
  dashboardApprovals: '/dashboard/approvals',
  dashboardActivity: '/dashboard/activity',
  dashboardSystemHealth: '/dashboard/system-health',
  dashboardChannelPerformance: '/dashboard/channel-performance',
  dashboardConversionAnalytics: '/dashboard/conversion-analytics',

  // User Management sub-routes
  userApprovals: '/users/approvals',
  blockedUsers: '/users/blocked',
  userWallets: '/users/wallets',
  userReferrals: '/users/referrals',
  userDocuments: '/users/documents',
  userComplaints: '/users/complaints',
  userReviews: '/users/reviews',
  userTimeline: '/users/timeline',
  userActivityLogs: '/users/activity-logs',
  userFraudMonitoring: '/users/fraud-monitoring',
  userAuditLogs: '/users/audit-logs',

  // Partner Management sub-routes
  ispPartners: '/partners/isp',
  bspPartners: '/partners/bsp',
  businessSellers: '/partners/business-sellers',
  partnerApprovals: '/partners/approvals',
  kycApprovals: '/partners/kyc-approvals',
  partnerServiceApprovals: '/partners/service-approvals',
  branchApprovals: '/partners/branch-approvals',
  partnerWallets: '/partners/wallets',
  partnerBanking: '/partners/banking',
  partnerEmployees: '/partners/employees',
  partnerBranches: '/partners/branches',
  partnerServices: '/partners/services',
  partnerReviews: '/partners/reviews',
  partnerRevenue: '/partners/revenue',
  partnerFraud: '/partners/fraud',
  partnerAuditLogs: '/partners/audit-logs',

  // KYC Management sub-routes
  kycPending: '/kyc/pending',
  kycApproved: '/kyc/approved',
  kycRejected: '/kyc/rejected',
  kycReupload: '/kyc/reupload',
  kycAadhaar: '/kyc/aadhaar',
  kycPan: '/kyc/pan',
  kycGst: '/kyc/gst',
  kycDriving: '/kyc/driving-license',
  kycVoter: '/kyc/voter-id',
  kycSelfie: '/kyc/selfie',
  kycFaceMatch: '/kyc/face-match',
  kycVideo: '/kyc/video',
  kycRisk: '/kyc/risk',
  kycManual: '/kyc/manual',
  kycAnalytics: '/kyc/analytics',
  kycAuditLogs: '/kyc/audit-logs',
  kycReviewers: '/kyc/reviewers',

  // Business Management sub-routes
  businessAll: '/business/all',
  businessGst: '/business/gst',
  businessPan: '/business/pan',
  businessRegVerification: '/business/registration-verification',
  businessOwnership: '/business/ownership-verification',
  businessBranches: '/business/branches',
  businessServices: '/business/services',
  businessEmployees: '/business/employees',
  businessRevenue: '/business/revenue',
  businessReviews: '/business/reviews',
  businessCompliance: '/business/compliance',
  businessFraud: '/business/fraud-investigation',
  businessAuditLogs: '/business/audit-logs',

  // Branch Management sub-routes
  branchAll: '/branches/all',
  branchServices: '/branches/services',
  branchEmployees: '/branches/employees',
  branchBookings: '/branches/bookings',
  branchReviews: '/branches/reviews',
  branchAuditLogs: '/branches/audit-logs',

  // Service Management sub-routes
  serviceCreation: '/services/creation',
  serviceActivation: '/services/activation',
  serviceCategories: '/services/categories',
  serviceSubCategories: '/services/sub-categories',
  serviceAll: '/services/all',
  serviceAdd: '/services/add',
  serviceApprovals: '/services/approvals',
  servicePricing: '/services/pricing',
  serviceCommission: '/services/commission',
  serviceAreasList: '/services/areas',
  serviceAreaCoverage: '/services/coverage',
  servicePerformance: '/services/performance',
  serviceAnalytics: '/services/analytics',
  serviceFeatured: '/services/featured',
  serviceMedia: '/services/media',
  serviceAuditLogs: '/services/audit-logs',

  // Employee Management sub-routes
  employeeAll: '/employees/all',
  employeeAvailability: '/employees/availability',
  branchManagers: '/employees/branch-managers',
  employeeAssignments: '/employees/assignments',
  employeeDocuments: '/employees/documents',
  employeeEarnings: '/employees/earnings',
  employeeRatings: '/employees/ratings',
  employeeKyc: '/employees/kyc',
  employeeAnalytics: '/employees/analytics',
  employeeAuditLogs: '/employees/audit-logs',

  // Booking Management sub-routes
  bookingAll: '/bookings/all',
  bookingPending: '/bookings/pending',
  bookingAssigned: '/bookings/assigned',
  bookingAccepted: '/bookings/accepted',
  bookingInProgress: '/bookings/in-progress',
  bookingMaterialPending: '/bookings/material-pending',
  bookingQuotationPending: '/bookings/quotation-pending',
  bookingOtpPending: '/bookings/otp-pending',
  bookingCompleted: '/bookings/completed',
  bookingCancelled: '/bookings/cancelled',
  bookingCancellation: '/bookings/cancellation',
  bookingRefunded: '/bookings/refunded',
  bookingEscalated: '/bookings/escalated',
  bookingDisputed: '/bookings/disputed',
  bookingAssignmentCenter: '/bookings/assignment-center',
  bookingOtpVerification: '/bookings/otp-verification',
  bookingCalendar: '/bookings/calendar',
  bookingMap: '/bookings/map',
  bookingPayments: '/bookings/payments',
  bookingInvoices: '/bookings/invoices',
  bookingRefunds: '/bookings/refunds',
  bookingSla: '/bookings/sla',
  bookingAnalytics: '/bookings/analytics',
  bookingCommunications: '/bookings/communications',
  bookingReports: '/bookings/reports',
  bookingFraud: '/bookings/fraud',
  bookingArchive: '/bookings/archive',

  // Live Tracking sub-routes
  liveDashboard: '/live-tracking/dashboard',
  liveOpsMap: '/live-tracking/ops-map',
  liveActiveJobs: '/live-tracking/active-jobs',
  liveEmployeeTracking: '/live-tracking/employee',
  liveRouteTracking: '/live-tracking/routes',
  liveEta: '/live-tracking/eta',
  liveDelay: '/live-tracking/delays',
  liveGeofence: '/live-tracking/geofence',
  liveGeofenceLogs: '/live-tracking/geofence-logs',
  liveHistory: '/live-tracking/history',
  liveHeatmaps: '/live-tracking/heatmaps',
  liveSos: '/live-tracking/sos',
  liveAnalytics: '/live-tracking/analytics',

  // Material Management sub-routes
  materialRequests: '/materials/requests',
  materialCreate: '/materials/create',
  materialDetails: '/materials/details',
  materialApprovals: '/materials/approvals',
  materialInventory: '/materials/inventory',
  materialListing: '/materials/listing',
  materialCategories: '/materials/categories',
  materialRestocking: '/materials/restocking',
  materialVendors: '/materials/vendors',
  materialSupplierComparison: '/materials/suppliers-comparison',
  materialPurchaseOrders: '/materials/purchase-orders',
  materialDelivery: '/materials/delivery-tracking',
  materialConsumption: '/materials/consumption',
  materialReturns: '/materials/returns',
  materialSupplierPerformance: '/materials/supplier-performance',
  materialAnalytics: '/materials/analytics',
  materialReports: '/materials/reports',
  materialDisputes: '/materials/disputes',
  materialCostOptimization: '/materials/cost-optimization',

  // Quotation Management sub-routes
  quotationSeller: '/quotations/seller',
  quotationCustomer: '/quotations/customer',
  quotationCustomerDetails: '/quotations/customer/details',
  quotationRfq: '/quotations/rfq',
  quotationCreateRfq: '/quotations/rfq/create',
  quotationDetails: '/quotations/details',
  quotationApprovals: '/quotations/approvals',
  quotationApprovalDetail: '/quotations/approvals/detail',
  quotationComparison: '/quotations/comparison',
  quotationWinner: '/quotations/winner',
  quotationNegotiation: '/quotations/negotiation',
  quotationRevisions: '/quotations/revisions',
  quotationExpired: '/quotations/expired',
  quotationRejected: '/quotations/rejected',
  quotationGeneratePo: '/quotations/generate-po',
  quotationOrders: '/quotations/orders',
  quotationOrderDetails: '/quotations/orders/detail',
  quotationCommunication: '/quotations/communication',
  quotationCostOptimization: '/quotations/cost-optimization',
  quotationSellerPerformance: '/quotations/seller-performance',
  quotationAnalytics: '/quotations/analytics',
  quotationPricingAnalytics: '/quotations/pricing-analytics',
  quotationDisputes: '/quotations/disputes',
  quotationHighValue: '/quotations/high-value',
  quotationBulkApproval: '/quotations/bulk-approval',
  quotationReports: '/quotations/reports',

  // Wallet Management sub-routes
  walletAll: '/wallet/all',
  walletUser: '/wallet/user',
  walletPartner: '/wallet/partner',
  walletSeller: '/wallet/seller',
  walletEmployee: '/wallet/employee',
  walletTransactions: '/wallet/transactions',
  walletRefunds: '/wallet/refunds',
  walletPenalties: '/wallet/penalties',
  walletFreeze: '/wallet/freeze',
  walletFraud: '/wallet/fraud',
  walletAnalytics: '/wallet/analytics',
  walletReconciliation: '/wallet/reconciliation',
  walletEarnings: '/wallet/earnings',
  walletDashboard: '/wallet/dashboard',
  walletDetails: '/wallet/details/:id',
  transactionDetail: '/wallet/transactions/:id',
  walletAdjustment: '/wallet/adjustment',
  walletFreezeCenter: '/wallet/freeze-center',
  walletUnfreezeApproval: '/wallet/unfreeze-approval/:id',
  refundDashboard: '/wallet/refunds/dashboard',
  penaltyDetail: '/wallet/penalties/:id',
  walletSettlementDashboard: '/wallet/settlements/dashboard',
  walletSettlementDetail: '/wallet/settlements/:id',
  riskInvestigation: '/wallet/risk-investigation/:id',
  chargebackManagement: '/wallet/chargebacks',
  walletReports: '/wallet/reports',
  walletCommunication: '/wallet/communication',

  // Banking & Settlements sub-routes
  bankingDashboard: '/banking/dashboard',
  bankAccounts: '/banking/accounts',
  bankAccountDetails: '/banking/accounts/details',
  bankAccountAdd: '/banking/accounts/add',
  bankAccountEdit: '/banking/accounts/edit',
  bankBeneficiaries: '/banking/beneficiaries',
  bankUpi: '/banking/upi',
  bankVerificationQueue: '/banking/verification-queue',
  bankVerificationDetail: '/banking/verification-detail',
  withdrawalDashboard: '/banking/withdrawals/dashboard',
  withdrawalRequests: '/banking/withdrawals',
  withdrawalDetail: '/banking/withdrawals/detail',
  withdrawalApprovals: '/banking/withdrawals/approvals',
  settlementDashboard: '/banking/settlements/dashboard',
  settlementQueue: '/banking/settlement-queue',
  settlementDetail: '/banking/settlements/detail',
  bulkSettlements: '/banking/bulk-settlements',
  failedSettlements: '/banking/failed',
  bankingReconciliation: '/banking/reconciliation',
  reconciliationDetails: '/banking/reconciliation/detail',
  payoutProcessing: '/banking/payouts',
  financeApprovals: '/banking/finance-approvals',
  bankingAnalytics: '/banking/analytics',
  bankPerformance: '/banking/performance',
  bankingReports: '/banking/reports',
  bankingSettings: '/banking/settings',

  // Revenue Management sub-routes
  revenueDashboard: '/revenue/dashboard',
  revenueOverview: '/revenue/overview',
  revenueDaily: '/revenue/daily',
  revenueWeekly: '/revenue/weekly',
  revenueMonthly: '/revenue/monthly',
  revenueYearly: '/revenue/yearly',
  revenuePartner: '/revenue/partner',
  revenueSeller: '/revenue/seller',
  revenueBranch: '/revenue/branch',
  revenueEmployee: '/revenue/employee',
  revenueService: '/revenue/service',
  revenueProfitLoss: '/revenue/profit-loss',
  revenueExpenses: '/revenue/expenses',
  revenueForecasting: '/revenue/forecasting',
  revenueTargets: '/revenue/targets',
  revenueExecutive: '/revenue/executive',
  revenueBI: '/revenue/bi',
  revenueHealth: '/revenue/health',

  // Referral Management sub-routes
  referralDashboard: '/referrals/dashboard',
  referralListing: '/referrals/listing',
  referralCampaignDashboard: '/referrals/campaigns',
  referralCampaignListing: '/referrals/campaigns/list',
  referralCreateCampaign: '/referrals/campaigns/create',
  referralRewardApprovals: '/referrals/rewards/approvals',
  referralRewardSettlements: '/referrals/rewards/settlements',
  referralConversionAnalytics: '/referrals/conversion-analytics',
  referralSources: '/referrals/sources',
  referralLeaderboard: '/referrals/leaderboard',
  referralFraud: '/referrals/fraud',
  referralInvestigations: '/referrals/investigations',
  referralCoupons: '/referrals/coupons',
  referralQr: '/referrals/qr',

  // Notification Center sub-routes
  notificationsPush: '/notifications/push',
  notificationsSms: '/notifications/sms',
  notificationsWhatsapp: '/notifications/whatsapp',
  notificationsEmail: '/notifications/email',
  notificationsTemplates: '/notifications/templates',
  notificationsAudience: '/notifications/audience',
  notificationsScheduled: '/notifications/scheduled',
  notificationsAutomation: '/notifications/automation',
  notificationsDelivery: '/notifications/delivery-reports',
  notificationsInApp: '/notifications/in-app',


  // Banner Management sub-routes
  bannersHomepage: '/banners/homepage',
  bannersOffer: '/banners/offer',
  bannersCategory: '/banners/category',
  bannersPopup: '/banners/popup',
  bannersScheduling: '/banners/scheduling',
  bannersAnalytics: '/banners/analytics',

  // CMS Management sub-routes
  cmsAboutUs: '/cms/about-us',
  cmsTerms: '/cms/terms',
  cmsPrivacy: '/cms/privacy',
  cmsRefund: '/cms/refund',
  cmsContactUs: '/cms/contact-us',
  cmsFaqs: '/cms/faqs',
  cmsBlogs: '/cms/blogs',
  cmsSeo: '/cms/seo',

  // Reviews & Ratings sub-routes
  reviewsUser: '/reviews/user',
  reviewsPartner: '/reviews/partner',
  reviewsEmployee: '/reviews/employee',
  reviewsModeration: '/reviews/moderation',
  reviewsAnalytics: '/reviews/analytics',

  // SOS Management sub-routes
  sosDashboard: '/sos/dashboard',
  sosActive: '/sos/active',
  sosDetails: '/sos/details',
  sosDispatch: '/sos/dispatch',
  sosResolved: '/sos/resolved',
  sosEscalated: '/sos/escalated',
  sosTracking: '/sos/tracking',
  sosIncidentReports: '/sos/incidents',
  sosResponseQueue: '/sos/response-queue',
  sosCategories: '/sos/categories',
  sosContacts: '/sos/contacts',
  sosCommunication: '/sos/communication',
  sosResources: '/sos/resources',
  sosInvestigationCenter: '/sos/investigation-center',
  sosHeatmap: '/sos/heatmap',
  sosIncidentReportDetails: '/sos/incidents/detail',
  sosResolution: '/sos/resolution',
  sosPerformance: '/sos/performance',
  sosAnalytics: '/sos/analytics',
  sosFraud: '/sos/fraud-detection',
  sosInvestigation: '/sos/investigation',
  sosReports: '/sos/reports',
  sosSettings: '/sos/settings',
  sosAuthority: '/sos/authority-integration',
  sosAudit: '/sos/audit',
  sosCommandCenter: '/sos/command-center',

  // Support Center sub-routes
  supportAll: '/support/all',
  supportOpen: '/support/open',
  supportInProgress: '/support/in-progress',
  supportEscalated: '/support/escalated',
  supportClosed: '/support/closed',
  supportBookingIssues: '/support/bookings',
  supportPaymentIssues: '/support/payments',
  supportWalletIssues: '/support/wallet',
  supportTechnicalIssues: '/support/technical',
  supportKycIssues: '/support/kyc',
  supportSla: '/support/sla',
  supportAnalytics: '/support/analytics',
  supportDetails: '/support/ticket/:id',
  supportCreate: '/support/create',
  supportKb: '/support/kb',
  supportKbCreate: '/support/kb/create',
  supportFinancial: '/support/financial',
  supportOpsDashboard: '/support/ops-dashboard',
  supportOverview: '/support/overview',
  supportAutomation: '/support/automation',
  supportAgentWorkspace: '/support/agent-workspace',
  supportCommunications: '/support/communications',

  // Fraud Management sub-routes
  fraudDashboard: '/fraud/dashboard',
  fraudCases: '/fraud-management/cases',
  fraudCaseDetails: '/fraud-management/cases/detail',
  fraudRiskMonitoring: '/fraud-management/risk-monitoring',
  fraudUser: '/fraud/user',
  fraudPartner: '/fraud/partner',
  fraudEmployee: '/fraud-management/employee-fraud',
  fraudWallet: '/fraud/wallet',
  fraudPayment: '/fraud-management/payment-fraud',
  fraudReferral: '/fraud-management/referral-fraud',
  fraudKyc: '/fraud-management/kyc-fraud',
  fraudDevice: '/fraud-management/device-intelligence',
  fraudIp: '/fraud-management/ip-intelligence',
  fraudGeo: '/fraud-management/geo-fraud',
  fraudBooking: '/fraud/booking',
  fraudInvestigations: '/fraud/investigations',
  fraudWorkspace: '/fraud-management/investigator-workspace',
  fraudAlerts: '/fraud-management/alerts',
  fraudRisk: '/fraud/risk-scoring',
  fraudCompliance: '/fraud-management/compliance',
  fraudAml: '/fraud-management/aml',
  fraudAnalytics: '/fraud-management/analytics',
  fraudHeatmap: '/fraud-management/heatmap',
  fraudReports: '/fraud-management/reports',
  fraudResolution: '/fraud-management/resolution',
  blacklistManagement: '/fraud/blacklist',
  whitelistManagement: '/fraud-management/whitelist',
  fraudAutomation: '/fraud-management/automation-rules',
  fraudCommunication: '/fraud-management/communication',
  fraudAudit: '/fraud-management/audit',
  fraudExecutive: '/fraud-management/executive-dashboard',
  fraudAssignment: '/fraud-management/case-assignment',
  fraudRecovery: '/fraud-management/recovery',
  fraudIntegrations: '/fraud-management/integrations',
  fraudSettings: '/fraud-management/settings',

  // Reports & Analytics sub-routes
  reportsOperational: '/reports/operational',
  reportsBooking: '/reports/bookings',
  reportsUser: '/reports/users',
  reportsPartner: '/reports/partners',
  reportsEmployee: '/reports/employees',
  reportsFinancial: '/reports/financial',
  reportsRevenue: '/reports/revenue',
  reportsWallet: '/reports/wallet',
  reportsSettlement: '/reports/settlement',
  reportsMarketing: '/reports/marketing',
  reportsReferral: '/reports/referrals',
  reportsCampaign: '/reports/campaigns',
  exportCenter: '/reports/export',
  pdfExports: '/reports/export/pdf',
  excelExports: '/reports/export/excel',
  csvExports: '/reports/export/csv',

  // Role & Permission sub-routes
  rolePermissions: '/roles/admin',
  createRole: '/roles/create',
  permissionMatrix: '/roles/permissions',
  moduleAccess: '/roles/module-access',
  actionPermissions: '/roles/action-permissions',
  userAccessLogs: '/roles/user-access',
  roleAuditLogs: '/roles/audit-logs',

  // Settings sub-routes
  settingsPlatformGeneral: '/settings/platform/general',
  settingsPlatformConfig: '/settings/platform/configuration',
  settingsFinancialCommission: '/settings/financial/commission',
  settingsFinancialTax: '/settings/financial/tax',
  settingsFinancialWallet: '/settings/financial/wallet',
  settingsFinancialSettlement: '/settings/financial/settlement',
  settingsIntegrationPayment: '/settings/integration/payment-gateway',
  settingsIntegrationSms: '/settings/integration/sms-gateway',
  settingsIntegrationWhatsapp: '/settings/integration/whatsapp',
  settingsIntegrationEmail: '/settings/integration/email-smtp',
  settingsIntegrationGoogleMaps: '/settings/integration/google-maps',
  settingsSecurityGeneral: '/settings/security/general',
  settingsSecurityPassword: '/settings/security/password-policies',
  settingsSecuritySession: '/settings/security/session-management',
  settingsSecurityAudit: '/settings/security/audit-logs',
  settingsSystemBackup: '/settings/system/backup',
  settingsSystemMaintenance: '/settings/system/maintenance',
  settingsSystemLogs: '/settings/system/logs',
  
  // Notification Center Phase 2 Reorganized Routes
  notificationsApprovalQueue: '/notifications/approval-queue',
  notificationsReports: '/notifications/reports-export',
  notificationsGlobalNotifications: '/notifications/global-notifications',
  notificationsNotificationPreferences: '/notifications/notification-preferences',
  notificationsCommunicationLogs: '/notifications/communication-logs',
  notificationsNotificationCostCenter: '/notifications/notification-cost-center'
};
