export const ROUTES = {
  root: '/',
  roles: '/roles',
  login: '/login',
  forgotPassword: '/forgot-password',
  otpVerification: '/otp-verification',
  resetPassword: '/reset-password',
  passwordResetSuccess: '/password-reset-success',
  dashboard: '/dashboard',
  partners: '/partners',
  partnerDetails: '/partner-details',
  addPartner: '/partners/add',
  onboardingAddress: '/partners/onboarding-address',
  addServices: '/partners/add-services',
  addBanking: '/partners/add-banking',
  approvalQueue: '/partners/approval-queue',
  fraudCenter: '/fraud-detection',
  communications: '/communications',
  settlements: '/settlements',
  analytics: '/analytics',
  users: '/users',
  kyc: '/kyc',
  business: '/business',
  branches: '/branches',
  services: '/services',
  employees: '/employees',
  bookings: '/bookings',
  liveTracking: '/live-tracking',
  materials: '/materials',
  quotations: '/quotations',
  wallet: '/wallet',
  banking: '/banking',
  revenue: '/revenue',
  referrals: '/referrals',
  notifications: '/notifications',
  banners: '/banners',
  cms: '/cms',
  reviews: '/reviews',
  sos: '/sos',
  support: '/support',
  settings: '/settings'
};



